[package]
name = "wafflelink"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
smallvec = "1.4"
libc = "0.2"
lazy_static = "1.4"
cranelift = "0.64"
paste = "0.1"
cranelift-simplejit = "0.64"
atomig = {version = "0.1",features= ["derive"]}
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }

[features]
value32-64 = []
value64 = []
default = ["value64"]