[package]
name = "waffle"
version = "0.1.0"
authors = ["playXE <adel.prokurov@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.8"
lazy_static = "1.3"
structopt = "0.2"
walkdir = "2.2"
rayon = "1.1"