[package]
name = "waffle"
version = "0.1.0"
authors = ["playXE <adel.prokurov@protonmail.com>"]
edition = "2018"



[profile.release]
lto = true
opt-level = 3
codegen-units = 8
[dependencies]
colored = "1.8"
lazy_static = "1.3"
structopt = "0.2"
walkdir = "2.2"
rayon = "1.1"
cranelift = "0.30"
cranelift-module = "0.30"
cranelift-simplejit = "0.30"
cranelift-faerie = "0.30"
cranelift-preopt = "0.30"
time = "0.1"
target-lexicon = "0.3"
libc = "0.2"