[package]
name = "waffle"
version = "0.1.0"
authors = ["playXE <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
colored = "1.8"
lazy_static = "1.3"
walkdir = "2.2"
dirs = "2.0"
structopt = "0.2"