[package]
name = "wafflelink"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmimalloc-sys = {version = "0.1",features=["extended","secure"]}
time = "0.2"
bit-vec = "0.6"
intrusive-collections = "0.9"
rand = "0.7"
mimalloc = "0.1"
once_cell = "1.4.1"
libc = "0.2"
fxhash = "0.2"
parking_lot = "0.11"
[[bin]]
name = "cli"

[features]
default = []

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 'z'