[package]
authors = ["playX <adel.prokurov@protonmail.com>"]
edition = "2018"
name    = "wafflelink"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
masm = { path = "masm-rs" }
capstone = "0.7"
parking_lot = "0.11"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }

[features]
default    = ["value64"]
value32-64 = []
value64    = []
