[package]
name = "wafflelink"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2"
lazy_static = "1.4"
paste = "0.1"
ahash = "0.3.8"
murmur3 = "0.5"
parking_lot = "0.10"
memmap = "0.7"
log = "0.4"
bitfield = "*"
simple_logger = "1.6.0"
dashmap = "3.11"
atomig = {version = "0.1",features= ["derive"]}
setjmp = "0.1"
crossbeam-epoch = "0.8"
vec_map = "0.8.2"
bit-set = "0.5.2"
thread_local = "1.0.1"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }

[build-dependencies]
cc = "1.0"


[features]
value32-64 = []
value64 = []
use-vtable = []

default = ["value64"]

[profile.release]
debug = true
