[package]
name = "waffle2"
version = "0.1.0"
authors = ["playX <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
smallvec = "1.4"
lazy_static = "1.4"
dashmap = {version = "3.11"}
cfg-if = "0.1"
atomig = "0.1"
indexmap = "1.4"
parking_lot = {version = "0.10"}
[features]
value64 = []
value32-64 = []
default = ["value64"]

[profile.release]
opt-level=2
lto = true
codegen-units=1
panic = 'abort'
