[package]
name = "waffle2"
version = "0.1.0"
authors = ["playX <adel.prokurov@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"
hashlink = "0.5"
fancy-regex = "0.3"
indexmap = "1.3"
derive_more = "0.99"
smallvec = "*"
futures = "0.3"
log = "0.4"
libc = "0.2"
mimalloc = { version = "*", default-features = false }
hmap = "0.1"
chrono = "*"
bv = "0.11"
lazy_static = "1.4"
simple_logger = "1.6"
intrusive-collections = "0.9"
regalloc = "0.0"
capstone = "0.7"
[features]
value64 = []
value32-64 = []
default = ["value64","perf"]
perf = []

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["memoryapi"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "8.1.*"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.3"
