[package]
name = "wafflelink"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2"
lazy_static = "1.4"
paste = "0.1"
parking_lot = "0.10"
log = "0.4"
simple_logger = "1.6.0"
atomig = {version = "0.1",features= ["derive"]}
setjmp = "0.1"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }
[dependencies.tagged-box]
version = "0.1.1"
default-features = false
features = ["56bits"] # Select your feature here
[features]
value32-64 = []
value64 = []
use-vtable = []
default = ["value64"]

[profile.release]
debug = true