[package]
name = "wafflelink"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = {version = "0.1", optional = false}
time = "0.2"
once_cell = "1.4"
bit-set = "0.5.2"
intrusive-collections = "0.9"
[[bin]]
name = "cli"

