[package]
name = "waffle2"
version = "0.1.0"
authors = ["playX <adel.prokurov@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgc-single-threaded = "0.1"
hashlink = "0.5"
fancy-regex = "0.3"
derive_more = "0.99"
[features]
value64 = []
value32-64 = []
default = ["value64"]
