[package]
name = "wafflelink"
version = "0.1.0"
authors = ["playX <gtashnik11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmimalloc-sys = {version = "0.1",features=["extended"]}
time = "0.2"
[[bin]]
name = "cli"

